### ISSUE TITLE
'on eat [of <item types>]' event

### ISSUE THREAD

**Issue by Njol** [Njol/Skript#170]

**Comment by MiniUSB** [comment]
I'd love it if you can finish/fix this.

**Comment by Njol** [comment]
It's quite tricky as long as Bukkit doesn't provide the event itself.

**Comment by MiniUSB** [comment]
Wouldn't it be something like

onCookieAten{ Cookiesaten++ print(Cookiesaten); }

**Comment by Njol** [comment]
Well that assumes that there's an onCookieEaten event which there isn't.
