### ISSUE TITLE
Database support - store all or specific variables in a database

### ISSUE THREAD

**Issue by Njol** [Njol/Skript#187]

**Comment by Pr0Failure** [comment]
Please add this ASAP, I pretty much require it for the script I'm making, I can't seem to use what little of list variables already offer to fully complete what I had in mind,

**Comment by Frizi** [comment]
But it seems to be only an implementation detali, the usage of variables will stay the same. You can do pritty much anythink anyway. Or am i wrong maybe?

**Comment by Njol** [comment]
If you think that you need a database you should consider creating a real Java plugin =P

This feature was suggested by someone who has multiple servers and wants to synchronize player variales between them.

**Comment by THEr2d2** [comment]
Added the possibility to store the variables in the database is a brilliant idea.
This made ​​it possible to create such statistics, allowing the display of the contents of specific variables, such as through php page :) 
It would be allowed to hold a much larger number of variables than in the file.
The file can not store variables for 25,000 players :) Hmmmm 25,000 \* 5 variables per user = suicide :D

Please for a positive opinion to add MySql: D  Sorry for my English, I tried to write grammatically :)
