### ISSUE TITLE
'while' loop

### ISSUE THREAD

**Issue by Njol** [Njol/Skript#192]

**Comment by Frizi** [comment]
This must be added asap. There is no workaround. First i thought "tail recursion", then i noticed "there are no functions" :P

**Comment by Pr0Failure** [comment]
^ What he said, also for loops are greatly needed.

**Comment by Frizi** [comment]
If you have while loop, you can create for loop very easily.

**Comment by Njol** [comment]
You can use "Loop numbers/integers from x to y" as a for loop. I also added the while loop in beta 3 (I didn't ever test it though so it might not work at all ^^)

**Comment by joeuguce99** [comment]
I think you could as well do while loops with functions when implemented such as:

Function bla:
    (Insert stuff here)
    if {x} is equal to {y}:
        execute function bla

On skript load:
    execute function bla

**Comment by Njol** [comment]
Like previously mentionned while loops have been added in beta 3.

@joeuguce99 
I'll close all beta-related issues when the next stable version (2.0) will be released.
