### ISSUE TITLE
Document the code

### ISSUE THREAD

**Issue by Frizi** [Njol/Skript#196]
I wanted to add something, but it is sometimes hard to tell where should i begin. For example, what %something% or %something@-1% means inside patterns? There should be a documentation, because I (as many others) don't want to read the parser code because of adding a small thing.

**Comment by Njol** [comment]
If something isn't documented it's likely a hack I made for myself =3

The @-1/@1 for example automatically execute .setTime(-1/1) on the expression and print an error message if it doesn't have "time states" (I have to find a better word for this ^^)

I have to admit though that I didn't document patterns at all.

**Comment by Njol** [comment]
I wrote a bit on my pattern syntax here: http://wiki.njol.ch/skript:api#patterns
