### ISSUE TITLE
integer loop doesn't work on dynamic variables

### ISSUE THREAD

**Issue by Frizi** [Njol/Skript#198]
When passing variable to the `from..to` or `X times` loop and the value of passed variable is not directly assigned to constant expression (in other words, is not known at "compile time"), the loop wont execute.

example:

```
every 1 second:
    set {*loopCount} to 2
    add 3 to {*loopCount}
    broadcast "count: %{*loopCount}%"
    loop {*loopCount} times:
        broadcast "loop: %loop-integer%"
```

If you comment out the `add 3 to {*loopCount}` line, it would execute 2 times, otherwise never.
Resetting the variabe by another `set <constant expr>` after `add` will bring the loop back again (but this is pointless).

**Comment by Njol** [comment]
I'm already fixing numbers as they have been quite inconsistent. In the next release all numbers will be treated equally, e.g. you'll be able to write 'loop 5.6 times' and it will loop 5 times, but most importantly all expressions/effects/loops/etc. that use numbers will work with variables and other expressions that return numbers (e.g. amount of, id of, data value of, etc.)
