### ISSUE TITLE
Nested loops of the same type does not compile

### ISSUE THREAD

**Issue by Frizi** [Njol/Skript#200]
When I tried to do loop blocks in specific range inside other similar loop, I got the message, that loop-block is ambiguous. I think that the inner loop should have had the separated scope with its own version of this variable. Then when I need to bring back the outer loop value, I could just reassign it to other variable.

**Comment by Njol** [comment]
You're supposed to use loop-block-1/2/3/etc. respectively. I guess I'll improve the error message and improve the documentation ;)
