### ISSUE TITLE
Support for horses and other 1.6 features

### ISSUE THREAD

**Issue by joeuguce99** [Njol/Skript#231]

**Comment by Njol** [comment]
I added horses to the available entities and made health support fractions, is there more that was changed in 1.6?

**Comment by joeuguce99** [comment]
Hmmm... potion effects (saturation and absorption) and maybe playing sounds (/playsound) if bukkit added support for it.

**Comment by Njol** [comment]
Bukkit finally added a horse API, so Skript 2.1. will support those - but parsing horse colours and styles is not possible, only variations - donkeys, skeleton horses, etc. - as I was too lazy to figure out how to name all the possible options.
