### ISSUE TITLE
Add support for handling named items

### ISSUE THREAD

**Issue by Pilvinen** [Njol/Skript#232]
Dear Njol,
Please make this your number 1. priority and put everything else on hold :-)
We badly need a way of making at least semi-unique items in Minecraft
And this is the way to do it.

on left click:
  if player is holding a golden sword named "Njolbringer":
    if the amount of diamonds named "soul gem" in player's inventory is more than 0:
      message "Now I'm going to do some really really super cool stuff with this new fuctionality!"

on death of player:
  if the attacker is a player holding a golden sword named "Njolbringer":
    if the amount of diamonds named "empty soul gem" in attacker's inventory is more than 0:
      send "The black sword called %name of the item in hand of attacker% eats the soul of you enemy!"
      remove 1 diamond named "empty soul gem" from players' inventory
      give 1 diamond named "soul gem" to player's inventory

 Well, you get the general idea what I'm after. Sorry for the bad code.

**Comment by Njol** [comment]
beta 10 will be released as soon as it gets approved by the Bukkit staff an dwill include the following expressions:
http://njol.ch/projects/skript/doc/expressions/#ExprName
http://njol.ch/projects/skript/doc/expressions/#ExprNamed
