### ISSUE TITLE
Named condition detection not working on items that lose durability

### ISSUE THREAD

**Issue by Pilvinen** [Njol/Skript#233]
on left click:
  if player is holding iron sword named "&r<white>Talky":
    message "hello"

Does not work if the weapon is not in 100% condition. It works if the weapon is brand new.

But this works:

on left click:
  if player is holding iron sword:
    if name of player's tool is "&r<white>Talky":

**Comment by joeuguce99** [comment]
Make sure you are downloading the correct beta 10: http://dev.bukkit.org/bukkit-plugins/skript/files/74-2-0-beta-10-zip/

**Comment by Pilvinen** [comment]
Indeed I am. I have the release version installed and running. But if it pleases you, I will download using the link you provided and test it again.

**Comment by Pilvinen** [comment]
Confirmed again with link provided.

**Comment by Njol** [comment]
I recently became aware of this issue as well and will fix it in the next version.
