### ISSUE TITLE
YAML-like multiline string support.

### ISSUE THREAD

**Issue by ghost** [Njol/Skript#241]
Like in the answers from Matt Williamson and JohnS in the following Stackoverflow link:
http://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines

**Comment by Njol** [comment]
Currently the configs and scripts use exactly two special characters: ":" and "=". I'll rather not add more to keep scripts easy to write.
Also, any decent text editor can wrap lines automatically, so adding a way to do that manually doesn't make much sense.

**Comment by ghost** [comment]
Ok, thanks for the answer. Just one more question: How can I add linebreaks to strings? \n didn't work when I tried it yesterday.

**Comment by Njol** [comment]
This doesn't work yet as Skript assumes all Strings to be one-lined (e.g. player names, sign lines, or chat messages). Even if you could define multi-line strings in the config it could cause issues as of now, so I don't know whether I'll add this.

**Comment by ghost** [comment]
Ok, thanks.
