### ISSUE TITLE
book support

### ISSUE THREAD

**Issue by T3sT3ro** [Njol/Skript#244]
events:
-on book read
-on book open
-on book close
-on book sign
-on next page turn
-on previous page turn
-on book edit
conditions:
-is clear - if book is clear
-is signed
-is unsigned - while book is written but unsigned
-can read/can read page Xxx of book Yyy
-author - ie. if author of book has permission/ if author of book Yyy is Zzz
-is reading - if player is reading book - signed book
-is writing - if player is writing book - unsigned book
-page - ie. if player is holding book [optional-named Xxx] opened on page Xxx
effects:
-sign a book
-unsign a book
-give clear book to player
-give book #0001 [or give book named "mysavedbook"]
-save book - saves book to "books" folder [skript/books]
-load book "mynewbook" - loads book from "books" folder
-clear book - clears book
-rename book
-edit book - unsign book and make it editable
-send book - sends book to another player
-set books [load/give/save/read] priority to [0,1,2,3,4,5] - it sets which book will be given/saved/loaded first and forces player to read it if priority is 5 and if it's 0 - he can't read it until priority not change. if priority is 1 - nothing happens 2 - reminds player once per day to read book 3- remains till every real 15 minutes 4 - remains till every minute. if player read book with priority 2,3,4,5 - priority sets to 1
-open book to player
-edit page Xxx- edit only page Xxx - rest is uneditable
-edit line Zzz on Xxx page of Yyy book - the same as there ↑↑↑
-reload book folder - reload all books folder - the same as /skript reload all
-open page Xxx of book Yyy to player
expressions:
-book - is clear etc.
-reader 
-writer - NOT author but person, who edit the book
-author - author of signed book

All book must be in folder "books" and have .bk extension. it would be editable in notepad++ BUT each line must be separated by $1 [text], each page must be separated by @ ie. @1$1 first book line @1$2 second book line; if file is named LOL-my book.bk - the name of book in game will be "LOL-my book" on top of each file it must be name of author preceded by ! - ie. !Njol - in game author of book is "Njol". # - these are comments the same as in normal book. if somebody wants !,@,$,# marks in his book, he must double it ie. @1$1 do u see this? - @@

~~~REMEMBER !~~~ 
There are maximum 50 pages in one book, 256 characters on each page, 13 lines, and 19 characters in each line !!! The name of book is 16 letters, but its editable in anvil

**Comment by joeuguce99** [comment]
When I read "books folder" I thought this would be more of an add-on for Skript. I'm not sure what Njol would think about, but I'm sure a few couple of this features could certainty be added. I also think some of the features like opening the book are client side, not server side, so they might not be possible.

**Comment by T3sT3ro** [comment]
good attention- this is only idea ;) i think books support will be very useful
