### ISSUE TITLE
Some Supports For script :)

### ISSUE THREAD

**Issue by PoweredDragon** [Njol/Skript#247]
Crafting Support:
New text File - Skript Folder>Crafting
How can you make recipe?

In event On Craft:

On Craft:
1st crafting slot is [Item] {named} [name]:
2nd crafting slot is [Item] {named} [name]:
3rd crafting slot is [Item] {named} [name]:
[.....]
Give 1 [Item] {named} [name] to Crafting slot

Slots:
1 2 3
4 5 6  C
7 8 9

C = Crafting slot

And it will be Signed in this text file:
# [Item Name]

C: [Item], [Name]
1: [Item], [Name]
2: [Item], [Name]
[.....]
9: [Item], [Name]

Fireworks support:

Effects:

Shoot a firework from player:

Shoot a green,creeper firework from player
Shoot a green,ball firework from player
Shoot a firework in the direction of player
Spawn a firework at player:

Spawn A blue firework at the player
Spawn a yellow,big,creeper firework at the player

Spawn/shoot [colour{White = Default}], [size{Small = Default}], [shape{ball = Default}], [Fly Duration{10 = default}]

Conditions:

Firework Colour:

Green, Yellow, Blue, etc.

Firework Shape:

Ball, creeper, etc.

Firework size:

Big, Small

Fly Duration:

0, 1, 2, etc
0 = Explosion at the start :)

**Comment by Njol** [comment]
I definitely won't add recipe files or whatever to Skript, but I'll eventually add better slot support which could be used to do it like your first suggestion.

Furthermore please post the fireworks suggestions in the appropriate issue (#225).

**Comment by PoweredDragon** [comment]
So there will be possibility of our recipes in skript, by scripts :D ?

**Comment by Njol** [comment]
Well yes, but there might be other plugins that are suited better for creating recipes (e.g. RecipeManager if that still exists).

**Comment by PoweredDragon** [comment]
I know, but i like skript, it's really easy, and it will not be hard to do for players, when it'll be added :F
