### ISSUE TITLE
Lore

### ISSUE THREAD

**Issue by BoomShnizel** [Njol/Skript#253]
an option to add a lore to an item

**Comment by joeuguce99** [comment]
I tried to do this before, but how would you write it on a script?
EDIT: Probably "set lore %number% %item stack% to %text%"?

**Comment by zmolahah** [comment]
Was planning on suggesting this but thought it was suggested a while ago. I would think it would be cool like this, set lore -line number- of tool of player to "name" etc...

**Comment by Mirreski** [comment]
"Set %Item%'s lore line %number% to %text%" Would be nice in my opinion.

"Set tool of player's lore line 1 to "Admin Sword"
"Set tool of player's lore line 2 to "+1000 Damage"

Or as Joeuguce99 suggested. Or both.

**Comment by joshwenke** [comment]
Please add this! Would be really awesome :+1:
