### ISSUE TITLE
[Feature]On Tool Break

### ISSUE THREAD

**Issue by Pr0Failure** [Njol/Skript#259]
Couldn't find anything in the wiki or on forums, but could be useful for a lot of people.

**Comment by sebafudi** [comment]
would do such a thing. I'm working for a Magic item :D

(google translate :P)

**Comment by MostFunGuy** [comment]
Awesome, would this trigger for armor as well?

**Comment by Njol** [comment]
I found an event for tools, but not for armour unfortunately (it might still work for armour, but it's not documented).

**Comment by joshwenke** [comment]
Officially added in Skript 2.1.1! Link in documentation: http://njol.ch/projects/skript/doc/events/#item_break
