### ISSUE TITLE
Reload Error

### ISSUE THREAD

**Issue by G1R-Productions** [Njol/Skript#268]
When using the /reload command this error occurs:
http://pastebin.com/sw9MnFqa

The plugin also fails to load any scripts because of this even example scripts.

This is a ticket posted by someone else about the error:
http://dev.bukkit.org/bukkit-plugins/skript/tickets/294-mcpc-build-149-skript-error-on-load/

There are several other posts as well.

**Comment by Njol** [comment]
I usually use Bukkit tickets for bug reports, so I'll close this issue.
