### ISSUE TITLE
New Lines in Kick Messages

### ISSUE THREAD

**Issue by joshwenke** [Njol/Skript#272]
How would I go about adding new lines in kick messages? Is this even implimented in Skript yet, if not could it be a new feature?

**Comment by Njol** [comment]
Skript will eventually support multi-line strings, I'll at least create a 'line <x> of <text>' expression if possible (it conflicts with 'line <x> [of <block>]' currently - and I couldn't come up with a good solution to this issue yet)

**Comment by joeuguce99** [comment]
I really have not been in favour of multi-line support being a new type since in my opinion it will increase the length of the scripts. I believe we can use “\” or something like that to separate lines only in kick messages.
