### ISSUE TITLE
Expected TABs but got spaces

### ISSUE THREAD

**Issue by Pilvinen** [Njol/Skript#273]
Skript 2.1 Spigot 1.7.2 build 1202.

I have a bug. Spaces in scripts are not accepted anymore. Please fix asap :-)

[02:46:56 ERROR]: indentation error: expected 1 tab, but found 4 spaces (yski.sk line 136: send "%{_yskä.itselle}%" to {_pelaaja}')

ETC, every script every line.

"[02:46:56 INFO]: Loaded 53 scripts with a total of 165 triggers and 0 commands in 0.31 seconds
[02:46:56 INFO]: [Skript] Encountered 11388 errors while reloading the config and all scripts!"

**Comment by Pilvinen** [comment]
Unconfirmed? I don't like the sound of that. What can I do to help?

I tried making a simple skript:

on right click: <enter>
  player has permission "some.permission"
^-- two spaces

And saved it (OS: Ubuntu Linux, Editor: joe). And it fails with the "expected 1 tab found 2 spaces" message. The editor saves as utf-8 like the best of them and definitely does not add tabs anywhere / replace spaces with tabs or any of that funny stuff. It's really simple and straightforward console editor.

If I replace the spaces with tabs the skript works ok. I remove the tabs and replace them with spaces - it fails.

I don't know what else to tell you.

I'm not loving the prospect of having to edit over 11 thousand lines of code and replacing spaces with tabs to get back on the wagon.

**Comment by Pilvinen** [comment]
I tried a fresh install on a local test server.

It's having this same issue out of the box.

Cannot use spaces only tabs work.

Test machine has also Ubuntu Linux.

**Comment by MostFunGuy** [comment]
Known issue. Tabs are better anyway

**Comment by Pilvinen** [comment]
If you're such a fanboy feel free to edit my over ~17000 lines of code from spaces to tabs.

The nerve of some people... using spaces makes the code much more readable for me in the small wide screen 1920x1080 screen real estate that I have for coding.

I would really like this to get fixed. Keep your smug comments to yourself.

**Comment by Njol** [comment]
Will be fixed in the next version. You'll also be able to mix spaces and tabs in the same file (each trigger still has to stick to one type though).

**Comment by ghost** [comment]
Fixed in 2.1.1 - 2.1.2. Should be closed.
