### ISSUE TITLE
Mobs spawning uncontrollably in 2.1

### ISSUE THREAD

**Issue by Parrothead** [Njol/Skript#276]
On updating to 2.1, I found that even with all other scripts disabled that setting mob names seems to cause them to spawn uncontrollably over a short period of time.

set the display name of the zombie to "&rZombie"

I posted more info here: http://dev.bukkit.org/bukkit-plugins/skript/forum/help/60415-very-weird-2-1-bug/#p1

Unfortunately I don't think I can provide any server.log info because there's no error when this happens.  If you need more information, feel free to ask.

**Comment by Njol** [comment]
Maybe Minecraft doesn't take renamed mobs into account when determining how many mobs are alive, and spawns mobs until the server limit is hit. If those mobs are renamed again, MC will spawn even more mobs.

You could try to use either "display name" or "name" respectively and find out if that fixes the issue (Skript 2.1 introduced a difference between those two: http://njol.ch/projects/skript/doc/expressions/#ExprName)

**Comment by Parrothead** [comment]
I'm thinking that what you wrote might be correct, but I do remember Skript 2.0 not having this weird bug when I had names on the spawned mobs.  I'm still using 2.1, and I have a plugin that is currently stopping Minecraft from spawning these thousands of mobs by limiting the amount that can appear based on chunk count (http://dev.bukkit.org/bukkit-plugins/mobmanager/).  I'll see if I can find anything else that may be causing this.
