### ISSUE TITLE
Projectiles says they are Arrows. [2.1]

### ISSUE THREAD

**Issue by Mirreski** [Njol/Skript#277]
All projectiles or atleast Snowballs(Have not tested others) are displayed as "arrow" when doing "%projectile%".

On shoot:
    broadcast "%projectile%"
On projectile hit:
    broadcast "%projectile%"

Displays snowballs as "arrow".

Also setting a variable like this for example "set {Fire.Grenade::%projectile%} to projectile" in the on shoot event causes this error in the Server Log. 

Edit: When i changed (set {Fire.Grenade::%projectile%} to projectile) to (set {Fire.Grenade::%projectile%} to "Something Else") there was no error.

Error log: http://pastebin.com/FnQbATdY

**Comment by Njol** [comment]
Actually most entities will claim to be arrows. This will be fixed in the next version.
