### ISSUE TITLE
Skript crashes after reload command [Skript 2.0.2 , SkriptPlus 1.4]

### ISSUE THREAD

**Issue by T3sT3ro** [Njol/Skript#280]
This is from console after normal "reload" command:

http://pastebin.com/d3jckPtZ

And this is crash report after running my custom command from script:

http://pastebin.com/pwC4SH5h

**Comment by XHawk87** [comment]
Using the reload command on a live server is a bad idea for [many reasons](https://forums.bukkit.org/threads/petition-to-remove-the-reload-command.43212/). I really wouldn't expect something as complex as Skript to function properly afterwards.
