### ISSUE TITLE
Stabilise 2.1

### ISSUE THREAD

**Issue by joeuguce99** [Njol/Skript#283]
People have also said 2.0 is “easier” to use. Apparently people did not enjoy the "advanced syntax" feature.

**Comment by Njol** [comment]
2.1 doesn't remove anything or change the syntax, it just adds the possibility to group expressions in case Skript's parser does something that you didn't intend.

Also 2.1 doesn't allow spaces in scripts due to an error, which will be fixed in 2.1.1.
