### ISSUE TITLE
[Suggestion] Multiple mysql tables

### ISSUE THREAD

**Issue by Tsugaga** [Njol/Skript#284]
- Add a setting to name the default table
- Add table expression/effect
- Move variables from 1 table to another

Examples:

set {var} to 1
This saves the var in the default table.

set {var} to 1 in table "test"
This saves the var in the test table

transfer {var} to table "test"

if table of {var} is "test"

**Comment by Njol** [comment]
You can define multiple databases in 2.1 (not tables yet), and define which variables should be saved where. To transfer variables you have to rename that variable though (as the name determines where it will be saved). This ensures that scripts are portable and don't depend on the actual server configuration.

**Comment by Tsugaga** [comment]
Bumping this since 2.1 has been out for a little bit. I already knew multiple database were being added, my suggestion was for multiple tables. Using multiple databases is great for connecting multiple servers, but making multiple databases on the same server just for skript isn't practical. Why was this suggestion discarded?
