### ISSUE TITLE
Coloured permission messages

### ISSUE THREAD

**Issue by zmolahah** [Njol/Skript#287]
Allows colours to be used in permission messages without actually putting player has permission "permission.node" in a trigger.

Example:
http://pastebin.com/3Ct4dJjv

Or it can just stay as permission message and simply allow colours. Works already with usage.

Also I've noticed putting a permission in a command as this:
http://pastebin.com/9geT1Fd6

Does not work either. I was trying to make it so that if people can use /name they can use /nameme aswell but it does not read the permission as node or node. I usually just put it all in a trigger but I feel like using those ways from now on just to keep the scripts neat

**Comment by Njol** [comment]
Will be fixed in 2.1.1.
