### ISSUE TITLE
Skript 2.1 Not saving Variables

### ISSUE THREAD

**Issue by Ackuraku** [Njol/Skript#289]
Not sure if it was already noted, but the version 2.1 Skript that was taken down on the Bukkit page would not save any variables to either .csv or MySQL. Everything else besides that I tried out worked fine! Love the new features in 2.1 and am excited for its re-release, Thanks!!

**Comment by Njol** [comment]
Ouch, what a stupid mistake. This will of course be fixed ASAP.

**Comment by ghost** [comment]
Should have been fixed, you can close this issue.
