### ISSUE TITLE
Adding map images

### ISSUE THREAD

**Issue by leoforney** [Njol/Skript#290]
Hi NJOL! I love Skript so much and I think it would be cool to import maps so you can set the map to a url image. You can also modify it if it is in an item frame :D this would be really cool thanks!

**Comment by Njol** [comment]
I think that this is out of the scope of Skript. You can easily use another plugin's commands in scripts to achieve the same effect.

**Comment by joeuguce99** [comment]
I might make an addon with support for everything like this (of course if destroyer doesn't do it before me).

**Comment by leoforney** [comment]
@Njol 
  Ok thanks!

@joeuguce99 
  Cool! I can't wait if it will be released!

**Comment by joeuguce99** [comment]
Destroyer4017 added it to Skript Plus 2.0.
