### ISSUE TITLE
Region conditions

### ISSUE THREAD

**Issue by zmolahah** [Njol/Skript#291]
I know 2.1 is not actually released yet and I'm sure you already have this planned but just incase. Someone wanted a script made for them with WorldGuard support and I tried to make it for them but sadly I can't do everything he wanted because I need some conditions like this:

() = optional

If entity is in region (region)
(Checks if players or other entities are in a region)

if block is in region (region)
(Can be used to stop blocks from being broken or other things. I know you can do this already in WorldGuard but I prefer things to be handled through Skript it adds more possibilities)

if region region is set
(Checks if a region exists with WorldGuard)

also it would be nice if I could use name of region as well as just region so then I can use the name of a region more easily instead of it being called region in world world

**Comment by Njol** [comment]
All of these will be in 2.1, except that you have to use a slightly different syntax to check for any region ('region at <location> exists')
