### ISSUE TITLE
Change a default item name

### ISSUE THREAD

**Issue by zmolahah** [Njol/Skript#295]
Permanently change an item's name so that when it is crafted, droped, spawned in from creative, etc... It is named something different. Examples:

item names:
iron sword = "&fSteel sword"
tnt = "&4&lBOMB"
cake, cake block = "&6CAKE &7[&cNot a Lie&7]"

**Comment by joshwenke** [comment]
Oooh. Please! +1

**Comment by Njol** [comment]
You could do this yourself if Skript supported all 'item create' events that exist (I don't know if spawning an item in creative even causes an event). So I won't add this myself, but I could add those missing events if they exist.
