### ISSUE TITLE
[Bug] Zombies are called arrows in skript 2.1

### ISSUE THREAD

**Issue by zmolahah** [Njol/Skript#296]
Very strange but using this code:
on right click on entity:
    message "%clicked entity%"
I right clicked a zombie and it was called an arrow
http://puu.sh/73eoW.jpg

**Comment by Zerkhan** [comment]
« Actually most entities will claim to be arrows. This will be fixed in the next version. »
( Njol, commented 17 days ago )

**Comment by Njol** [comment]
Temporary fix ;) :

```
on spawn:
    entity is not an arrow
    delete the entity
    spawn an arrow
```
