### ISSUE TITLE
[Bug] Can't use arguments when enchanting items

### ISSUE THREAD

**Issue by zmolahah** [Njol/Skript#297]
Here is my code:
http://pastebin.com/wFhPwD9m

Here is my error message:
http://puu.sh/73iZF.jpg

**Comment by Njol** [comment]
You cannot yet mix all kinds of expressions, in particular "%enchantment% %level%" requires both parts to be static (i.e. not variables or other expressions, but text and numbers). I might rewrite my parser in the future to allow this and many other such constructs, but I currently don't have any idea how to do this.
