### ISSUE TITLE
Custom Commands no longer work when executed by plugins in CraftBukkit 1.7.2-R0.4 snapshots

### ISSUE THREAD

**Issue by XHawk87** [Njol/Skript#299]
It looks like Bukkit has undergone some considerable changes to how plugin commands are handled in the last couple of weeks, so that the Skript PluginCommand reflection hack is no longer effective. This makes Skript incompatible with a number of plugins that allow or involve command scripting.

**Comment by Njol** [comment]
will be fixed.

**Comment by XHawk87** [comment]
Excellent. So far I am recommending that my users don't upgrade past CB #3008. Just hope you can beat the next beta.

**Comment by Njol** [comment]
You could try the next version already if you want: https://dl.dropboxusercontent.com/u/48570304/Skript/Skript-2.1.1.jar

It should be mostly stable, though I have only tested variables and databases so far (which is the main part of the update).

**Comment by XHawk87** [comment]
I tested triggering a custom command from a CreateYourOwnMenus menu item. It worked perfectly. No other issues found with the build so far.

**Comment by ghost** [comment]
It should have been fixed in 2.1.2
"Fixed an error related to commands in the newer Bukkit builds". @Njol, I think, you can close this issue without doubt.
