### ISSUE TITLE
Add UUID Support for 1.8

### ISSUE THREAD

**Issue by Parrothead** [Njol/Skript#308]
Unless a better method comes up, I think UUIDs should be a new, seperate expression from %player%.  %UUID of player% or %player's ID% should be considered as many people use variables like {location.%player%} and it could cause issues if %player% starts grabbing ID's instead of usernames.

More info at 

http://dev.bukkit.org/bukkit-plugins/skript/forum/misc/63889-how-will-skript-react-to-1-8-uuids-and-username-changes/

and

http://storify.com/Marc_IRL/minecraft-username-changes

and

http://www.reddit.com/r/admincraft/comments/1zo4qg/dinnerbone_says_next_snapshot_contains_major_step/

**Comment by ghost** [comment]
Added in 2.1.2, issue should be closed.
