### ISSUE TITLE
On respawn/death screen/menu

### ISSUE THREAD

**Issue by marium0505** [Njol/Skript#328]
Hello.

I would love it if you added an on respawn/death screen/menu event.
This should fire whenever a player dies, and the respawn menu opens (the menu where you can click whether you want to respawn or go leave the server.

The reason I want this is so I can cancel it/prevent it from opening.
I know a plugin already can do this, so it must be possible.

**Comment by beastzone** [comment]
Go to the skript forum suggestions someone made a add on for it that works perfectly fine. I use it for all my mini game plugins. I would give you the link but I am on my phone at the moment.
