### ISSUE TITLE
loop blocks/entities in chunks

### ISSUE THREAD

**Issue by zmolahah** [Njol/Skript#336]
Not found a way to do this. The ability to loop blocks/entities in a chunk

example 1:
loop blocks in chunk at location of player:
    y coord of loop-block is greater than 49
    set loop-block to bedrock
    y coord of loop-block is greater than 50
    set loop-block to air

example 2:
loop entities in chunk at location of player:
    loop-entity is creeper
    kill loop-entity

**Comment by ismooch** [comment]
example 2:
loop entities in radius 16 of player:
chunk at location of loop-entity is chunk at location of player
loop-entity is creeper
kill loop-entity

**Comment by zmolahah** [comment]
Was already using that method previously. You can do the same method with the looping of blocks but it's not as good as looping the chunk.

Reason 1:
Does not loop everything you want unless you increase the radius by a large amount

Reason 2:
Will check for blocks/entities not even in the chunk which is just unnecessary

**Comment by joeuguce99** [comment]
Skript Plus already adds that.
