### ISSUE TITLE
Permission groups

### ISSUE THREAD

**Issue by marium0505** [Njol/Skript#337]
Hello.

There's one thing I have missed a lot, and that is the ability to use the following conditions:

Condition: "If player's (permission) group is [group]"

Condition: "if player's (permission group is not [group]"

And the following expression:

Expression: "%player's group%"

This would be awesome.

To check the primary group of a player you can use this: http://mythcraft.duckdns.org/javadoc/vault/net/milkbowl/vault/permission/Permission.html#playerInGroup(org.bukkit.entity.Player,%20java.lang.String)

It would be great if you could loop (or somehow run code for) all players in a permission group too.

I hope this gets added!

**Comment by marium0505** [comment]
Still hoping this will be added soon!

**Comment by MostFunGuy** [comment]
This was added by Umbaska
