### ISSUE TITLE
Play effects and sounds

### ISSUE THREAD

**Issue by Njol** [Njol/Skript#34]

**Comment by h3nryum** [comment]
effects such as "MOBSPAWNER_FLAMES" ( the flames that are surrounding a mobspawner) should be able to be applied using something like:
play effect "effect" at player    | play effect "effect at "location"
play sound "sound" at player  | play sound "sound" at "location"

**Comment by joeuguce99** [comment]
...and maybe music or being able to access the entire resources folder like in /playsound
