### ISSUE TITLE
On chat event is broken

### ISSUE THREAD

**Issue by ghost** [Njol/Skript#343]
Skript 2.1.2

on chat:
++++++++replace every "bad", "more", and "anybadword" with "good" in the message

Plus = space. I wrote them here to show you the script is correct. And it worked maybe on 2.0.2. Now it doesn't work.

UPD: Oh, yeah! Only Skript 2.0.2 works correctly with on chat event. Something is broken in newer versions. Njol, I'm praying you to fix that.

**Comment by ghost** [comment]
Anybody?

**Comment by Mirreski** [comment]
The code works perfectly for me(Im using 2.1.2) and Chat event has never been broken for as long i can remember as there is rarely changes to that event. It is likely that you are doing something wrong. Any errors?

**Comment by ghost** [comment]
I had to load script before other. Closed.
