### ISSUE TITLE
Skript testing module for Node.js

### ISSUE THREAD

**Issue by leoforney** [Njol/Skript#346]
Hi, I would love to test my Skripts to see if they work using Travis-CI or PHPCI. By making a Node.js module or Python/Ruby script you can check the syntax and report back the errors. This would be very cool and helpful... Thanks!

**Comment by joeuguce99** [comment]
What do you mean?

**Comment by leoforney** [comment]
Like if you write your code to a .sk file to a folder. You would run a command in shell like `skript test FunTest.sk` and if you have errors it would report with the amount of syntax errors or errors in running the command..

**Comment by joeuguce99** [comment]
I'm making an online project to write scripts with error checking included. Don't expect it soon though.

**Comment by leoforney** [comment]
Ok thanks :+1:
