### ISSUE TITLE
Pull numbers out of a string

### ISSUE THREAD

**Issue by G1R-Productions** [Njol/Skript#350]
The ability to properly pull out numbers from a string of words and numbers. I want to be able to take a string like this abcdefg 1 fgdhdb 2 and be able to recognize the numbers and pull them out like %num 1% %num 2% as well as for the non number text %variable 1% %variable 2%

Something similar to this quote:
"There used to be a way you could indicate "%text%:%number%"

And it would know to grab the text and number seperately. There is no best way to do that now."

See recent posts on:
http://dev.bukkit.org/bukkit-plugins/skript/forum/help/67422-trouble-with-pattern-parsing/#posts

**Comment by joeuguce99** [comment]
See #342.
