### ISSUE TITLE
bug with sounds in skript+

### ISSUE THREAD

**Issue by T3sT3ro** [Njol/Skript#351]
I'm using skript Hookshot from skript forum, but when i try to reload skript i got that bugs:
http://scr.hu/0g2f/za2cl
command play raw sound works great, but only play no D:
pls help me, script works fine, but i can't hear voices... before update of skript+ i could hear them
script Hookshot on pastebin:
http://pastebin.com/qpheWEU5

**Comment by joeuguce99** [comment]
Report it to Destroyer4017. Bugs reported here should only involve Skript itself, not any other add-on. ;D
