### ISSUE TITLE
Trying to open a Chest GUI

### ISSUE THREAD

**Issue by Sambish** [Njol/Skript#363]
Hello,

I'm trying to make a command in Skript where it'll open a Chest GUI to the player. But when I perform the command in-game, this error appears in the console:

02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#! 
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#! End of Error.
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#! 
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#! Thread: Server thread
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#! 
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#! Current item: open inventory to the player
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#! Current node: null
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#! 
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#! Running CraftBukkit: false
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#! 
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!   Java: 1.7.0_71
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!   Minecraft: 1.7.10
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!   Bukkit: 1.7.10-R0.1-SNAPSHOT
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!   Skript: 2.1.2
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#! Version Information:
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#! 
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1132)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1328)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at java.lang.reflect.Method.invoke(Method.java:606)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at sun.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:155)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:260)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:193)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at ch.njol.skript.util.Task.callSync(Task.java:139)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand$1.call(ScriptCommand.java:1)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand$1.call(ScriptCommand.java:220)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:50)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at ch.njol.skript.effects.EffOpenInventory.execute(EffOpenInventory.java:78)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:61)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:101)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at com.w00tmast3r.skquery.elements.expressions.ExprBlankInventories.get(ExprBlankInventories.java:14)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at com.w00tmast3r.skquery.elements.expressions.ExprBlankInventories.get(ExprBlankInventories.java:36)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at org.bukkit.Bukkit.createInventory(Bukkit.java:629)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_7_R4.CraftServer.createInventory(CraftServer.java:1565)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_7_R4.inventory.CraftInventoryCustom.<init>(CraftInventoryCustom.java:27)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_7_R4.inventory.CraftInventoryCustom$MinecraftInventory.<init>(CraftInventoryCustom.java:54)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#!     at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#! java.lang.IllegalArgumentException: Title cannot be longer than 32 characters
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#! Stack trace:
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#! 
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#! and check whether this error has already been reported.
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#! 
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#! [Skript] Severe Error:
02.11 08:43:44 [Server] INFO [08:43:44 ERROR]: #!#! 
02.11 08:43:44 [Server] INFO [08:43:44 INFO]: sambish20: /promo
02.11 08:43:41 [Server] INFO [08:43:41 INFO]: [Poke-Trainer]Duck_Daan: but ALFA_17 did u pay?
02.11 08:43:34 [Server] INFO [08:43:34 INFO]: [Ghost-Gym]Bryan: buying breeders
02.11 08:43:32 [Server] INFO [08:43:32 INFO]: The One and Only [Poke-Trainer]belic10 has appeared!
02.11 08:43:32 [08:43:32 INFO]: belic10 ran command Message of the Day
02.11 08:43:32 [Connect] User [08:43:32 INFO]: belic10, IP 124.178.70.29
02.11 08:43:32 [Server] INFO [08:43:32 INFO]: [Server thread] Server side modded connection established
02.11 08:43:31 [Server] INFO [08:43:31 INFO]: Attempting connection with missing mods [ivsevs, PixelExtras, wondertrade] at CLIENT
02.11 08:43:31 [Server] INFO [08:43:31 INFO]: Client attempting to join with 4 mods : mcp@9.05,FML@7.10.18.1180,Forge@10.13.0.1180,pixelmon@3.3.3
02.11 08:43:31 [Server] INFO [08:43:31 INFO]: Client protocol version 1
02.11 08:43:30 [Server] INFO [08:43:30 INFO]: Wave goodbye to [Poke-Trainer]Icurrie!
02.11 08:43:30 [Server] INFO [08:43:30 INFO]: UUID of player belic10 is 42f24224-7f57-49f0-a682-6145fb632d40
02.11 08:43:29 [Disconnect] User [08:43:29 INFO]: Icurrie has disconnected, reason: Disconnected
02.11 08:43:22 [Server] INFO [08:43:22 INFO]: Wave goodbye to [Poke-Trainer]belic10!
02.11 08:43:21 [Disconnect] User [08:43:21 INFO]: belic10 has disconnected, reason: Disconnected
02.11 08:43:20 [Server] INFO [08:43:20 INFO]: Player has a pokemon in a ranch block which isn't in their pc
02.11 08:43:20 [Server] INFO [08:43:20 INFO]: Player has a pokemon in a ranch block which isn't in their pc
02.11 08:43:19 [Server] INFO [08:43:19 INFO]: Player has a pokemon in a ranch block which isn't in their pc
02.11 08:43:19 [Server] INFO [08:43:19 INFO]: Player has a pokemon in a ranch block which isn't in their pc
02.11 08:43:12 [Server] INFO [08:43:12 ERROR]: #!#! 
02.11 08:43:12 [Server] INFO [08:43:12 ERROR]: #!#! End of Error.
02.11 08:43:12 [Server] INFO [08:43:12 ERROR]: #!#! 
02.11 08:43:12 [Server] INFO [08:43:12 ERROR]: #!#! Thread: Server thread
02.11 08:43:12 [Server] INFO [08:43:12 ERROR]: #!#! 
02.11 08:43:12 [Server] INFO [08:43:12 ERROR]: #!#! Current item: open inventory to the player
02.11 08:43:12 [Server] INFO [08:43:12 ERROR]: #!#! Current node: null
02.11 08:43:12 [Server] INFO [08:43:12 ERROR]: #!#! 
02.11 08:43:12 [Server] INFO [08:43:12 ERROR]: #!#! Running CraftBukkit: false
02.11 08:43:12 [Server] INFO [08:43:12 ERROR]: #!#! 
02.11 08:43:12 [Server] INFO [08:43:12 ERROR]: #!#!   Java: 1.7.0_71
02.11 08:43:12 [Server] INFO [08:43:12 ERROR]: #!#!   Minecraft: 1.7.10
02.11 08:43:12 [Server] INFO [08:43:12 ERROR]: #!#!   Bukkit: 1.7.10-R0.1-SNAPSHOT
02.11 08:43:12 [Server] INFO [08:43:12 ERROR]: #!#!   Skript: 2.1.2
02.11 08:43:12 [Server] INFO [08:43:12 ERROR]: #!#! Version Information:
02.11 08:43:12 [Server] INFO [08:43:12 ERROR]: #!#! 
02.11 08:43:12 [Server] INFO [08:43:12 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
02.11 08:43:12 [Server] INFO [08:43:12 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)

Thanks,
Sam.

**Comment by Njol** [comment]
"Title cannot be longer than 32 characters"

apparently you cannot use inventory names longer than 32 characters. Try 
to use a shorter name to see if the error vanishes.

Am 02.11.2014 14:45, schrieb Sam Bishop:

> Title cannot be longer than 32 characters

**Comment by Sambish** [comment]
Ah, thanks, I didn't even notice that.
