### ISSUE TITLE
Incompatibility between Skript and MassiveCore ( That makes Skript "freezed" )

### ISSUE THREAD

**Issue by Beerus-Sama** [Njol/Skript#376]
Hi , i find a big problem , there's an problem when massivecore and Skript are running at the same time , it's making skript not working and massivecraft more laggy , i opened a ticket on the massivecore github and it seems that the problem is from skript ! ( [Here's the link](https://github.com/MassiveCraft/MassiveCore/issues/266#issuecomment-230073371) )
I'm here for find a way to solve the problem thanks you :smile:

**Comment by TlatoaniHJ** [comment]
Njol isn't active, so you will probably not get a response here. I recommend you go to https://forums.skunity.com and post a help thread.

**Comment by Beerus-Sama** [comment]
Ok i'm going to post a thread
