### ISSUE TITLE
Allow variables to hold multiple values

### ISSUE THREAD

**Issue by Njol** [Njol/Skript#54]
ideas:

```
# add a new element:
add <something> to {variable}[]
# get an element:
{variable}[<index>]
# set an element:
set {variable}[<index>] to <whatever>
# insert an element:
insert <whatever> into {variable}[] after/before [<index>]/<value>
# remove an element:
remove <whatever>/[<index>] from {variable}[]
# loop elements:
loop {variable}[]:
  # can use loop-value and loop-index here
```

{variable}[] can also be replaced by something else but it should distinguish single-element variables from multi-element variables.

Indices can be anything?

**Comment by Frizi** [comment]
What about `{variable.%{*index}%}`?

**Comment by Njol** [comment]
Well I chose {variable::index} for an element in a list and {variable::*} for the whole list ATM (beta).
